### ISSUE TITLE
🚨MALWARE WARNING🚨

### ISSUE THREAD

**Issue by louislang** [banus-finance-org/auth-sandbox#1]
### ☠️ THIS IS MALWARE ☠️   

Forking and setting up this repository will install **malware** onto your machine. In [models/utils.min.js](https://github.com/banus-finance-org/auth-sandbox/blob/eb7010f33abe54e3ab0d859920160a88093dbb01/models/utils.min.js) you will find the obfuscated code for known malware.

For more detailed information on this and why its malware, please see: https://blog.phylum.io/smuggling-malware-in-test-code/

**Comment by BlockchainDeveloper1** [comment]
Sir is this a fake job posting ?

**Comment by louislang** [comment]
Yes, it is, do not fork and run this. Whoever is running this account is attempting to install malware on your machine.

**Comment by BlockchainDeveloper1** [comment]
sir i am also just going to run this repo on my system they told me that it is for live coding interview software which i have to install it but before i do it i found your warning and also read article then i resend email but there is no response from there side.
well thank you sir for saving me and lots of job seekers and i also shared this issues on Linkedln for aware people https://www.linkedin.com/feed/update/urn:li:activity:7166304820264435712/  
Thank You Again Sir.

**Comment by louislang** [comment]
Oh good, I'm glad we were able to help!
